steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: $(project)
    pipeline: $(ciPipeline)
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    artifactName: 'drop'
    targetPath: '$(Pipeline.Workspace)'

- task: AzureFunctionApp@1
  displayName: 'Deploy'
  inputs:
    azureSubscription: 'fulfill3d-subscription-alpha'
    appType: functionApp
    appName: $(functionAppName)
    package: '$(Pipeline.Workspace)/**/$(packageName).zip'
