steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: |
      $(workingDirectory)/*.csproj
    arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release
    version: '8.x'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(packageName).zip
    replaceExistingArchive: true

- publish: $(Build.ArtifactStagingDirectory)/$(packageName).zip
  artifact: drop
