apiVersion: v1
kind: Secret
metadata:
  name: eventhub-secret
type: Opaque
stringData:
  EVENTHUB_CONNECTION_STR: "<EVENT_HUB_CONNECTION_STRING>"

---
apiVersion: v1
kind: Secret
metadata:
  name: servicebus-secret
type: Opaque
stringData:
  SERVICEBUS_CONNECTION_STR: "<SERVICE_BUS_CONNECTION_STRING>"
